LOAD LIBRARIES

In [6]:
import oracle_repo as orep
import importlib
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from torch.utils.data import Dataset, DataLoader
from sentence_transformers import SentenceTransformer, util

/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange

CREATE A STORAGE OBJECT FOR MODEL OUTPUT and VECTOR OUTPUT THAT REMAINS VALID OVER ITERATIONS

In [4]:
response_outputs_backup = []
training_data = []

RESET THE RESPONSE OBJECT

In [5]:
response_outputs = []

PRECONFIGURE THE PARAMETERS

In [7]:
# Define the problem type
# Example usage with user input
problem_types = ["deterministic", "predictive", "code_based", "philosophical"]

print("Choose problem type:")
for p_type in problem_types:
    print(f"- {p_type}")

# Get user input for problem type
problem_type = input("Enter the problem type: ").strip().lower()

if problem_type not in problem_types:
    raise ValueError("Invalid problem_type provided")

Choose problem type:
- deterministic
- predictive
- code_based
- philosophical

In [8]:
problem_scope = ["open", "closed"]

print("Choose problem scope:")
for p_type in problem_scope:
    print(f"- {p_type}")

# Get user input for problem type
problem_scope = input("Enter the problem type (open or closed problem?): ").strip().lower()

if problem_scope not in problem_scope:
    raise ValueError("Invalid problem_type provided")

Choose problem scope:
- open
- closed

In [9]:
#Initialize parameters
adaptation_rate = 0 #initialize adaptation rate.
messages = [] #cache to store list of best_responses for each request iteration t.
best_response_backup = []
num_steps_proposed = 0

#fill first iteration of feature vector with zeros to demarcarte start of an iteration cycle
feature_vector = (0, 0, 0, 0, 0, 0, [0, 0, 0, 0], 0, 0, 0, 0, 0)
training_data.append(feature_vector)

INITIALIZE MODEL

In [10]:
import yaml
import os
import openai as OpenAI
import openai
import json


# Load the YAML file
with open('config.yaml', 'r') as file:
    config = yaml.safe_load(file)

# Get the API key from the YAML file
api_key = config['openai']['api_key']

from pathlib import Path
import time
    
# Initialize the OpenAI client
client = openai.OpenAI(api_key=api_key)

#initialize request parameters
n_models = 2
system_task = "Invent rules for a board game with a scoring system on a 1-step scale and play that game until you reach score 5. Respond with 'FINISH' once a player has reached score 5. Do not ever mention the word 'FINISH' unless a player has reached 5 points."#
#"Order a Pizza near the Giesing Brewery in Munich. Deliver it to the following address: Arcisstraße 21, 80333 Munich, Germany. Payment with be handled by a human upon arrival of the pizza. Respond with 'FINISH' when you are done."task_step = system_task
num_step = 0
response = "Null"
task_step=system_task

orep.openai_request(client, n_models, num_step, system_task, task_step, response, response_outputs)

{
  "steps": [
    "- Define the objective of the game.",
    "- Determine the number of players.",
    "- Create the game board layout.",
    "- Establish the rules for player movement.",
    "- Define how players can score points.",
    "- Set up any special rules or conditions.",
    "- Play the game according to the rules until a player reaches 5 points."
  ]
}
{
  "tasks": [
    "- Define the objective of the game.",
    "- Determine the number of players.",
    "- Create the game board layout.",
    "- Establish the rules for player movement.",
    "- Define how players can score points.",
    "- Set up any special conditions or events.",
    "- Outline the winning conditions.",
    "- Play the game step-by-step until a player reaches 5 points."
  ]
}

GENERATE TRAINING PARAMETERS

In [11]:
fitness_scores = []

for response in response_outputs:
    response = response[num_step]
    text = list(json.loads(response['message']).values())[0]
    ag_rationality, model_type_label, agent_type_label = orep.evaluate_fitness(response["model_type"], response["agent_type"], problem_type)
    fitness_scores.append(ag_rationality)

# Calculate consensus score
consensus_score = orep.calculate_consensus_score(response_outputs)

# Calculate the action maximization score for each response
act_max_scores = []
for fitness in fitness_scores:
    ag_rationality = fitness
    act_max_score = orep.calculate_act_max_score(ag_rationality, consensus_score)
    act_max_scores.append(act_max_score)

/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [12]:

# # Output the scores
# for i, response in enumerate(responses):
#     print(f"Response from {response['model_type']} - Agent Rationality: {fitness_scores[i][0]}, Act Max Score: {act_max_scores[i]}")

# Select the best response
best_response_index = act_max_scores.index(max(act_max_scores))
best_response = response_outputs[best_response_index]
best_response_backup.append(best_response)
model_type = best_response[0]["model_type"]
act_max_score = max(act_max_scores)

messages.append(best_response)

In [13]:
error_rate = orep.evaluate_error_rate(messages[0][num_step]['message'], best_response_backup)
best_response_body = list(json.loads(best_response[num_step]['message']).values())[0]

In [14]:
problem_scope_label, problem_type_label, num_step, num_agents, num_steps_proposed, ratio_steps_left = orep.evaluate_environment_complexity(problem_scope, problem_type, num_step, n_models, best_response_body, num_steps_proposed)

In [15]:
#generate input vector

#orep.generate_feature_vector(act_max_score, model_type, problem_scope, problem_type, num_step, n_models, best_response_body, adaptation_rate, agent_type='LLM')

feature_vector = act_max_score, ag_rationality, model_type_label, agent_type_label, adaptation_rate, problem_scope_label, problem_type_label, num_step, n_models, num_steps_proposed, ratio_steps_left, error_rate

training_data.append(feature_vector)

In [18]:
best_response_body

['- Define the objective of the game.',
 '- Determine the number of players.',
 '- Create the game board layout.',
 '- Establish the rules for player movement.',
 '- Define how players can score points.',
 '- Set up the initial game state.',
 '- Play the game, taking turns according to the rules.',
 '- Track the score of each player.',
 '- Continue playing until a player reaches 5 points.',
 '- Declare the winner once a player reaches 5 points.']

UPDATE REQUEST PARAMETERS

In [16]:
task_step = best_response_body[num_step]
num_steps_proposed = len(best_response_body)
num_step =+ 1
response_outputs_backup.append(response_outputs)
response_outputs = []

orep.openai_request(client, n_models, num_step, system_task, task_step, response, response_outputs)

{
  "message": {
    "steps": [
      "- Define the objective of the game.",
      "- Determine the number of players.",
      "- Create the game board layout.",
      "- Establish the rules for player movement.",
      "- Define how players can score points.",
      "- Set up any special conditions or events.",
      "- Outline the winning conditions.",
      "- Play the game step-by-step until a player reaches 5 points."
    ],
    "solution": {
      "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges."
    }
  }
}
{
  "message": {
    "steps": [
      "- Define the objective of the game.",
      "- Determine the number of players.",
      "- Create the game board layout.",
      "- Establish the rules for player movement.",
      "- Define how players can score points.",
      "- Set up any special conditions or events.",
      "- Outline the winning conditions.",
      "- Play the game step-by-step until a player reaches 5 points."
    ],
    "solution": {
      "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges."
    }
  }
}

####
####INITIALIZE SUBSEQUENT RUNS
####

In [21]:
import json
import pandas as pd

def auto_generate_feature_vector(response_outputs, num_step, problem_scope, problem_type, n_models, adaptation_rate, num_steps_proposed, response_outputs_backup):
    """
    Generate a feature vector based on the responses and environment complexity.

    Args:
    - response_outputs: List of responses from the models.
    - num_step: Current step number.
    - problem_scope: Scope of the problem.
    - problem_type: Type of the problem.
    - n_models: Number of models.
    - adaptation_rate: Rate of adaptation (default is 0).

    Returns:
    - feature_vector: A tuple containing the feature vector.
    """
    # Initialize lists to store scores
    fitness_scores = []
    act_max_scores = []

    # Evaluate fitness for each response
    for response in response_outputs:
        response = response[num_step]
        #text = list(json.loads(response['message']).values())[0]
        ag_rationality, model_type_label, agent_type_label = orep.evaluate_fitness(response["model_type"], response["agent_type"], problem_type)
        fitness_scores.append(ag_rationality)

    # Calculate consensus score
    consensus_score = orep.calculate_consensus_score(response_outputs)

    # Calculate action maximization scores
    for fitness in fitness_scores:
        ag_rationality = fitness
        act_max_score = orep.calculate_act_max_score(ag_rationality, consensus_score)
        act_max_scores.append(act_max_score)

    # Select the best response
    best_response_index = act_max_scores.index(max(act_max_scores))
    best_response = response_outputs[best_response_index]
    best_response_backup.append(best_response)
    model_type = best_response[num_step]["model_type"]
    model_type_label = {"gpt-3.5": 1, "gpt-4": 2, "gpt-4o": 2, "gemini": 3, "gemini-ultra": 4, "mistral": 5}[model_type] #convert model type to label

    act_max_score = max(act_max_scores)

    messages = [best_response]
    #ro_df_columns = ["model_1", "model_2"]
    if num_step > 1:
        last_responses = [response_outputs_backup[num_step], response_outputs_backup[num_step-1]]
        error_rate = orep.evaluate_error_rate(messages[0][num_step]['message'], best_response_backup, responses=last_responses, num_step=num_step)
    else:
        error_rate = orep.evaluate_error_rate(messages[0][num_step]['message'], best_response_backup, responses=None, num_step=num_step)

    best_response_body = list(json.loads(best_response[num_step]['message']).values())[0]
    print(best_response_body, error_rate)

    problem_scope_label, problem_type_label, num_step, n_models, num_steps_proposed, ratio_steps_left = orep.evaluate_environment_complexity(
        problem_scope, problem_type, num_step, n_models, best_response_body, num_steps_proposed)

    # Generate the feature vector
    feature_vector = (
        act_max_score,
        ag_rationality,
        model_type_label,
        agent_type_label,
        adaptation_rate,
        problem_scope_label,
        problem_type_label,
        num_step,
        n_models,
        num_steps_proposed,
        ratio_steps_left,
        error_rate
    )

    return feature_vector, best_response_body

In [18]:
def contains_finish(response_outputs_backup):
    for response in response_outputs_backup:
        if isinstance(response, list):
            for sub_response in response:
                for key, value in sub_response.items():
                    if 'message' in value:
                        message = value['message']
                        if isinstance(message, dict):
                            if any("FINISH" in msg for msg in message.values()):
                                return True
                        elif isinstance(message, str):
                            if "FINISH" in message:
                                return True
        elif isinstance(response, dict):
            for key, value in response.items():
                if 'message' in value:
                    message = value['message']
                    if isinstance(message, dict):
                        if any("FINISH" in msg for msg in message.values()):
                            return True
                    elif isinstance(message, str):
                        if "FINISH" in message:
                            return True
    return False

In [22]:
response_outputs_backup

[[{0: {'model_type': 'gpt-4o',
    'agent_type': 'LLM',
    'message': '{\n  "steps": [\n    "- Define the objective of the game.",\n    "- Determine the number of players.",\n    "- Create the game board layout.",\n    "- Establish the rules for player movement.",\n    "- Define how players can score points.",\n    "- Set up the initial game state.",\n    "- Play the game, taking turns according to the rules.",\n    "- Track the score of each player.",\n    "- Continue playing until a player reaches 5 points.",\n    "- Declare the winner once a player reaches 5 points."\n  ]\n}'}},
  {0: {'model_type': 'gpt-4o',
    'agent_type': 'LLM',
    'message': '{\n  "tasks": [\n    "- Define the objective of the game.",\n    "- Determine the number of players.",\n    "- Create the game board layout.",\n    "- Establish the rules for player movement.",\n    "- Develop a scoring system on a 1-step scale.",\n    "- Set the conditions for winning the game.",\n    "- Play the game according to the rules until a player reaches a score of 5."\n  ]\n}'}}]]

In [19]:
def process_steps(response_outputs, best_response_body, num_step, problem_scope, problem_type, n_models, adaptation_rate, num_steps_proposed, response_outputs_backup, sub_layer=0, finished=False):
    bullet_markers = ['-', '*', '•']
    finished = finished
    i = len(best_response_body) * 2
    j = 0

    while not finished:
        
        feature_vector, response = auto_generate_feature_vector(response_outputs, num_step, problem_scope, problem_type, n_models, adaptation_rate, num_steps_proposed, response_outputs_backup)
        training_data.append(feature_vector)
        
        task_step = best_response_body[num_step]
        if num_step < (len(best_response_body) - 1):
            num_step += 1
        
        response_outputs_backup.append(response_outputs)
        response_outputs = []
        sub_layer = 0

        orep.openai_request(client, n_models, num_step, system_task, task_step, response, response_outputs)

        if any("FINISH" in output for output in response_outputs):
            return True, sub_layer
        #THIS NEEDS A GLOBAL VARIABLE THAT IS EITHER 1 OR 0 AND PROHIBITS THE ESTABLISHMENT OF DEEPER LOOP LAYERS IF 1.
        # If the response contains sub-steps, process them recursively
        for response in response_outputs:
            response_body = json.loads(response[num_step]['message'])

            if 'message' not in response_body:
                response_body['message'] = str(response_body)
            
            if 'steps:' in response_body['message']:
                sub_steps = []
                for line in response_body['message'].split('\n'):
                    if any(line.strip().startswith(marker) for marker in bullet_markers):
                        sub_steps.append(line.strip())
                
                if sub_steps and sub_layer == 0:
                    sub_layer += 1
                    sub_response_body = ", ".join(sub_steps)
                    for step in sub_steps:
                        finished, sub_layer = process_steps(response_outputs, sub_response_body, num_step, problem_scope, problem_type, n_models, adaptation_rate, num_steps_proposed, response_output_backup, sub_layer)
                        return finished, sub_layer
                    
            elif 'steps:' in response_body:
                sub_steps = []
                for line in response_body['message'].split('\n'):
                    if any(line.strip().startswith(marker) for marker in bullet_markers):
                        sub_steps.append(line.strip())
                
                if sub_steps and sub_layer == 0:
                    sub_layer += 1
                    sub_response_body = ", ".join(sub_steps)
                    for step in sub_steps:
                        finished, sub_layer = process_steps(response_outputs, sub_response_body, num_step, problem_scope, problem_type, n_models, adaptation_rate, num_steps_proposed, response_output_backup, sub_layer)
                        return finished, sub_layer
                    
        print("updated sub_layer equals:" + str(sub_layer))
        j += 1
        if j == i:
            break
    return False, sub_layer

In [35]:
responses = [response_outputs_backup[num_step][0], response_outputs_backup[num_step-1][0]]
responses

[{1: {'model_type': 'gpt-4o',
   'agent_type': 'LLM',
   'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game.",\n      "- Determine the number of players.",\n      "- Create the game board layout.",\n      "- Establish the rules for player movement.",\n      "- Define how players can score points.",\n      "- Set up any special conditions or events.",\n      "- Outline the winning conditions.",\n      "- Play the game step-by-step until a player reaches 5 points."\n    ],\n    "solution": {\n      "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges."\n    }\n  }\n}'}},
 {0: {'model_type': 'gpt-4o',
   'agent_type': 'LLM',
   'message': '{\n  "steps": [\n    "- Define the objective of the game.",\n    "- Determine the number of players.",\n    "- Create the game board layout.",\n    "- Establish the rules for player movement.",\n    "- Define how players can score points.",\n    "- Set up any special rules or conditions.",\n    "- Play the game according to the rules until a player reaches 5 points."\n  ]\n}'}}]

In [38]:
parsed_responses = []
for response in responses:
    if isinstance(response, dict):
        for key in response:
            if isinstance(response[key], dict) and 'message' in response[key]:
                parsed_message = json.loads(response[key]['message'])
                parsed_responses.append(parsed_message)
    elif isinstance(response, dict) and 'message' in response:
        parsed_message = json.loads(response['message'])
        parsed_responses.append(parsed_message)
print("parsed_responses: ")
print(parsed_responses)

parsed_responses:
[{'message': {'steps': ['- Define the objective of the game.', '- Determine the number of players.', '- Create the game board layout.', '- Establish the rules for player movement.', '- Define how players can score points.', '- Set up any special conditions or events.', '- Outline the winning conditions.', '- Play the game step-by-step until a player reaches 5 points.'], 'solution': {'objective': 'The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges.'}}}, {'steps': ['- Define the objective of the game.', '- Determine the number of players.', '- Create the game board layout.', '- Establish the rules for player movement.', '- Define how players can score points.', '- Set up any special rules or conditions.', '- Play the game according to the rules until a player reaches 5 points.']}]

In [39]:
importlib.reload(orep)

In [114]:
# [list(json.loads((response[num_step][next(iter(response[i]))]['message'])).values()) for response in responses for i in range((len(responses)))]

[[{'steps': ['- Define the objective of the game.',
    '- Determine the number of players.',
    '- Create the game board layout.',
    '- Establish the rules for player movement.',
    '- Develop a scoring system on a 1-step scale.',
    '- Set the conditions for winning the game.',
    '- Play the game according to the rules until a player reaches a score of 5.'],
   'solution': {'objective': 'The objective of the game is to navigate the game board, collect points, and be the first player to reach a score of 5.'}}],
 [{'steps': ['- Define the objective of the game.',
    '- Determine the number of players.',
    '- Create the game board layout.',
    '- Establish the rules for player movement.',
    '- Develop a scoring system on a 1-step scale.',
    '- Set the conditions for winning the game.',
    '- Play the game according to the rules until a player reaches a score of 5.'],
   'solution': {'objective': 'The objective of the game is to navigate the game board, collect points, and be the first player to reach a score of 5.'}}],
 [['- Define the objective of the game.',
   '- Determine the number of players.',
   '- Create the game board layout.',
   '- Establish the rules for player movement.',
   '- Develop a scoring system on a 1-step scale.',
   '- Set the conditions for winning the game.',
   '- Play the game according to the rules until a player reaches a score of 5.']],
 [['- Define the objective of the game.',
   '- Determine the number of players.',
   '- Create the game board layout.',
   '- Establish the rules for player movement.',
   '- Develop a scoring system on a 1-step scale.',
   '- Set the conditions for winning the game.',
   '- Play the game according to the rules until a player reaches a score of 5.']]]

In [130]:
# responses = [response_outputs_backup[num_step][0], response_outputs_backup[num_step-1][0]]
# responses
# #[list(json.loads((response[num_step][next(iter(response[i]))]['message'])).values()) for response in responses for i in range(len(response))]
# orep.evaluate_error_rate(messages[0][0]['message'], best_response_backup, responses=responses, num_step=num_step)

0.0

In [98]:
# [list(json.loads((response[num_step][next(iter(response[i]))]['message'])).values()) for response in responses for i in range(len(response))]

[[{'steps': ['- Define the objective of the game.',
    '- Determine the number of players.',
    '- Create the game board layout.',
    '- Establish the rules for player movement.',
    '- Develop a scoring system on a 1-step scale.',
    '- Set the conditions for winning the game.',
    '- Play the game according to the rules until a player reaches a score of 5.'],
   'solution': {'objective': 'The objective of the game is to navigate the game board, collect points, and be the first player to reach a score of 5.'}}],
 [{'steps': ['- Define the objective of the game.',
    '- Determine the number of players.',
    '- Create the game board layout.',
    '- Establish the rules for player movement.',
    '- Develop a scoring system on a 1-step scale.',
    '- Set the conditions for winning the game.',
    '- Play the game according to the rules until a player reaches a score of 5.'],
   'solution': {'objective': 'The objective of the game is to navigate the game board, collect points, and be the first player to reach a score of 5.'}}],
 [['- Define the objective of the game.',
   '- Determine the number of players.',
   '- Create the game board layout.',
   '- Establish the rules for player movement.',
   '- Develop a scoring system on a 1-step scale.',
   '- Set the conditions for winning the game.',
   '- Play the game according to the rules until a player reaches a score of 5.']],
 [['- Define the objective of the game.',
   '- Determine the number of players.',
   '- Create the game board layout.',
   '- Establish the rules for player movement.',
   '- Develop a scoring system on a 1-step scale.',
   '- Set the conditions for winning the game.',
   '- Play the game according to the rules until a player reaches a score of 5.']]]

In [2]:
    responses = [
        json.loads(responses[i][key]['message'])
        for i in range(len(responses))
        for key in responses[i]
    ]
    ##--> need to test this object, as consensus score and error rate are called twice in the script for different dict object structures...

NameError: name 'responses' is not defined

In [47]:
finished = False
sub_layer = 0

finished, sub_layer = process_steps(response_outputs, best_response_body, num_step, problem_scope, problem_type, n_models, adaptation_rate, num_steps_proposed, response_outputs_backup, sub_layer)

response:
{1: {'model_type': 'gpt-4o', 'agent_type': 'LLM', 'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game.",\n      "- Determine the number of players.",\n      "- Create the game board layout.",\n      "- Establish the rules for player movement.",\n      "- Define how players can score points.",\n      "- Set up any special conditions or events.",\n      "- Outline the winning conditions.",\n      "- Play the game step-by-step until a player reaches 5 points."\n    ],\n    "solution": {\n      "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges."\n    }\n  }\n}'}}
parsed_responses:
[{'message': {'steps': ['- Define the objective of the game.', '- Determine the number of players.', '- Create the game board layout.', '- Establish the rules for player movement.', '- Define how players can score points.', '- Set up any special conditions or events.', '- Outline the winning conditions.', '- Play the game step-by-step until a player reaches 5 points.'], 'solution': {'objective': 'The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges.'}}}]
response:
{1: {'model_type': 'gpt-4o', 'agent_type': 'LLM', 'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game.",\n      "- Determine the number of players.",\n      "- Create the game board layout.",\n      "- Establish the rules for player movement.",\n      "- Define how players can score points.",\n      "- Set up any special conditions or events.",\n      "- Outline the winning conditions.",\n      "- Play the game step-by-step until a player reaches 5 points."\n    ],\n    "solution": {\n      "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges."\n    }\n  }\n}'}}
parsed_responses:
[{'message': {'steps': ['- Define the objective of the game.', '- Determine the number of players.', '- Create the game board layout.', '- Establish the rules for player movement.', '- Define how players can score points.', '- Set up any special conditions or events.', '- Outline the winning conditions.', '- Play the game step-by-step until a player reaches 5 points.'], 'solution': {'objective': 'The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges.'}}}, {'message': {'steps': ['- Define the objective of the game.', '- Determine the number of players.', '- Create the game board layout.', '- Establish the rules for player movement.', '- Define how players can score points.', '- Set up any special conditions or events.', '- Outline the winning conditions.', '- Play the game step-by-step until a player reaches 5 points.'], 'solution': {'objective': 'The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges.'}}}]
{'steps': ['- Define the objective of the game.', '- Determine the number of players.', '- Create the game board layout.', '- Establish the rules for player movement.', '- Define how players can score points.', '- Set up any special conditions or events.', '- Outline the winning conditions.', '- Play the game step-by-step until a player reaches 5 points.'], 'solution': {'objective': 'The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges.'}} 0.0
{
  "steps": [
    "- Define the objective of the game.",
    "- Determine the number of players.",
    "- Create the game board layout.",
    "- Establish the rules for player movement.",
    "- Define how players can score points.",
    "- Set up any special conditions or events.",
    "- Outline the winning conditions.",
    "- Play the game step-by-step until a player reaches 5 points."
  ],
  "solution": {
    "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges.",
    "number_of_players": 2
  }
}
{
  "message": {
    "steps": [
      "- Define the objective of the game.",
      "- Determine the number of players.",
      "- Create the game board layout.",
      "- Establish the rules for player movement.",
      "- Define how players can score points.",
      "- Set up any special conditions or events.",
      "- Outline the winning conditions.",
      "- Play the game step-by-step until a player reaches 5 points."
    ],
    "solution": {
      "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges.",
      "number_of_players": 2
    }
  }
}
updated sub_layer equals:0
response:
{2: {'model_type': 'gpt-4o', 'agent_type': 'LLM', 'message': '{\n  "steps": [\n    "- Define the objective of the game.",\n    "- Determine the number of players.",\n    "- Create the game board layout.",\n    "- Establish the rules for player movement.",\n    "- Define how players can score points.",\n    "- Set up any special conditions or events.",\n    "- Outline the winning conditions.",\n    "- Play the game step-by-step until a player reaches 5 points."\n  ],\n  "solution": {\n    "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges.",\n    "number_of_players": 2\n  }\n}'}}
parsed_responses:
[{'steps': ['- Define the objective of the game.', '- Determine the number of players.', '- Create the game board layout.', '- Establish the rules for player movement.', '- Define how players can score points.', '- Set up any special conditions or events.', '- Outline the winning conditions.', '- Play the game step-by-step until a player reaches 5 points.'], 'solution': {'objective': 'The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges.', 'number_of_players': 2}}]
response:
{2: {'model_type': 'gpt-4o', 'agent_type': 'LLM', 'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game.",\n      "- Determine the number of players.",\n      "- Create the game board layout.",\n      "- Establish the rules for player movement.",\n      "- Define how players can score points.",\n      "- Set up any special conditions or events.",\n      "- Outline the winning conditions.",\n      "- Play the game step-by-step until a player reaches 5 points."\n    ],\n    "solution": {\n      "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges.",\n      "number_of_players": 2\n    }\n  }\n}'}}
parsed_responses:
[{'steps': ['- Define the objective of the game.', '- Determine the number of players.', '- Create the game board layout.', '- Establish the rules for player movement.', '- Define how players can score points.', '- Set up any special conditions or events.', '- Outline the winning conditions.', '- Play the game step-by-step until a player reaches 5 points.'], 'solution': {'objective': 'The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges.', 'number_of_players': 2}}, {'message': {'steps': ['- Define the objective of the game.', '- Determine the number of players.', '- Create the game board layout.', '- Establish the rules for player movement.', '- Define how players can score points.', '- Set up any special conditions or events.', '- Outline the winning conditions.', '- Play the game step-by-step until a player reaches 5 points.'], 'solution': {'objective': 'The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges.', 'number_of_players': 2}}}]
response:
[{1: {'model_type': 'gpt-4o', 'agent_type': 'LLM', 'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game.",\n      "- Determine the number of players.",\n      "- Create the game board layout.",\n      "- Establish the rules for player movement.",\n      "- Define how players can score points.",\n      "- Set up any special conditions or events.",\n      "- Outline the winning conditions.",\n      "- Play the game step-by-step until a player reaches 5 points."\n    ],\n    "solution": {\n      "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges."\n    }\n  }\n}'}}, {1: {'model_type': 'gpt-4o', 'agent_type': 'LLM', 'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game.",\n      "- Determine the number of players.",\n      "- Create the game board layout.",\n      "- Establish the rules for player movement.",\n      "- Define how players can score points.",\n      "- Set up any special conditions or events.",\n      "- Outline the winning conditions.",\n      "- Play the game step-by-step until a player reaches 5 points."\n    ],\n    "solution": {\n      "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges."\n    }\n  }\n}'}}]
parsed_responses:
[]
response:
[{1: {'model_type': 'gpt-4o', 'agent_type': 'LLM', 'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game.",\n      "- Determine the number of players.",\n      "- Create the game board layout.",\n      "- Establish the rules for player movement.",\n      "- Define how players can score points.",\n      "- Set up any special conditions or events.",\n      "- Outline the winning conditions.",\n      "- Play the game step-by-step until a player reaches 5 points."\n    ],\n    "solution": {\n      "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges."\n    }\n  }\n}'}}, {1: {'model_type': 'gpt-4o', 'agent_type': 'LLM', 'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game.",\n      "- Determine the number of players.",\n      "- Create the game board layout.",\n      "- Establish the rules for player movement.",\n      "- Define how players can score points.",\n      "- Set up any special conditions or events.",\n      "- Outline the winning conditions.",\n      "- Play the game step-by-step until a player reaches 5 points."\n    ],\n    "solution": {\n      "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges."\n    }\n  }\n}'}}]
parsed_responses:
[]
['- Define the objective of the game.', '- Determine the number of players.', '- Create the game board layout.', '- Establish the rules for player movement.', '- Define how players can score points.', '- Set up any special conditions or events.', '- Outline the winning conditions.', '- Play the game step-by-step until a player reaches 5 points.'] 0.0
{
  "message": {
    "steps": [
      "- Define the objective of the game.",
      "- Determine the number of players.",
      "- Create the game board layout.",
      "- Establish the rules for player movement.",
      "- Define how players can score points.",
      "- Set up any special conditions or events.",
      "- Outline the winning conditions.",
      "- Play the game step-by-step until a player reaches 5 points."
    ],
    "solution": {
      "Create the game board layout": {
        "board_size": "8x8 grid",
        "board_elements": [
          "Start position for each player",
          "Pathways for movement",
          "Special tiles (e.g., bonus points, traps)",
          "Finish line or goal area"
        ],
        "visual_representation": [
          ["S", ".", ".", ".", ".", ".", ".", "F"],
          [".", ".", ".", ".", ".", ".", ".", "."],
          [".", ".", ".", ".", ".", ".", ".", "."],
          [".", ".", ".", ".", ".", ".", ".", "."],
          [".", ".", ".", ".", ".", ".", ".", "."],
          [".", ".", ".", ".", ".", ".", ".", "."],
          [".", ".", ".", ".", ".", ".", ".", "."],
          ["S", ".", ".", ".", ".", ".", ".", "F"]
        ]
      }
    }
  }
}
{
  "message": {
    "steps": [
      "- Define the objective of the game.",
      "- Determine the number of players.",
      "- Create the game board layout.",
      "- Establish the rules for player movement.",
      "- Define how players can score points.",
      "- Set up any special conditions or events.",
      "- Outline the winning conditions.",
      "- Play the game step-by-step until a player reaches 5 points."
    ],
    "solution": {
      "Create the game board layout": {
        "board_size": "8x8 grid",
        "board_elements": [
          "Start position for each player",
          "Pathways for movement",
          "Special tiles (e.g., bonus points, traps)",
          "Finish line or goal area"
        ],
        "visual_representation": [
          ["S", ".", ".", ".", ".", ".", ".", "F"],
          [".", ".", ".", ".", ".", ".", ".", "."],
          [".", ".", ".", ".", ".", ".", ".", "."],
          [".", ".", ".", ".", ".", ".", ".", "."],
          [".", ".", ".", ".", ".", ".", ".", "."],
          [".", ".", ".", ".", ".", ".", ".", "."],
          [".", ".", ".", ".", ".", ".", ".", "."],
          ["S", ".", ".", ".", ".", ".", ".", "F"]
        ]
      }
    }
  }
}
updated sub_layer equals:0
response:
{3: {'model_type': 'gpt-4o', 'agent_type': 'LLM', 'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game.",\n      "- Determine the number of players.",\n      "- Create the game board layout.",\n      "- Establish the rules for player movement.",\n      "- Define how players can score points.",\n      "- Set up any special conditions or events.",\n      "- Outline the winning conditions.",\n      "- Play the game step-by-step until a player reaches 5 points."\n    ],\n    "solution": {\n      "Create the game board layout": {\n        "board_size": "8x8 grid",\n        "board_elements": [\n          "Start position for each player",\n          "Pathways for movement",\n          "Special tiles (e.g., bonus points, traps)",\n          "Finish line or goal area"\n        ],\n        "visual_representation": [\n          ["S", ".", ".", ".", ".", ".", ".", "F"],\n          [".", ".", ".", ".", ".", ".", ".", "."],\n          [".", ".", ".", ".", ".", ".", ".", "."],\n          [".", ".", ".", ".", ".", ".", ".", "."],\n          [".", ".", ".", ".", ".", ".", ".", "."],\n          [".", ".", ".", ".", ".", ".", ".", "."],\n          [".", ".", ".", ".", ".", ".", ".", "."],\n          ["S", ".", ".", ".", ".", ".", ".", "F"]\n        ]\n      }\n    }\n  }\n}'}}
parsed_responses:
[{'message': {'steps': ['- Define the objective of the game.', '- Determine the number of players.', '- Create the game board layout.', '- Establish the rules for player movement.', '- Define how players can score points.', '- Set up any special conditions or events.', '- Outline the winning conditions.', '- Play the game step-by-step until a player reaches 5 points.'], 'solution': {'Create the game board layout': {'board_size': '8x8 grid', 'board_elements': ['Start position for each player', 'Pathways for movement', 'Special tiles (e.g., bonus points, traps)', 'Finish line or goal area'], 'visual_representation': [['S', '.', '.', '.', '.', '.', '.', 'F'], ['.', '.', '.', '.', '.', '.', '.', '.'], ['.', '.', '.', '.', '.', '.', '.', '.'], ['.', '.', '.', '.', '.', '.', '.', '.'], ['.', '.', '.', '.', '.', '.', '.', '.'], ['.', '.', '.', '.', '.', '.', '.', '.'], ['.', '.', '.', '.', '.', '.', '.', '.'], ['S', '.', '.', '.', '.', '.', '.', 'F']]}}}}]
response:
{3: {'model_type': 'gpt-4o', 'agent_type': 'LLM', 'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game.",\n      "- Determine the number of players.",\n      "- Create the game board layout.",\n      "- Establish the rules for player movement.",\n      "- Define how players can score points.",\n      "- Set up any special conditions or events.",\n      "- Outline the winning conditions.",\n      "- Play the game step-by-step until a player reaches 5 points."\n    ],\n    "solution": {\n      "Create the game board layout": {\n        "board_size": "8x8 grid",\n        "board_elements": [\n          "Start position for each player",\n          "Pathways for movement",\n          "Special tiles (e.g., bonus points, traps)",\n          "Finish line or goal area"\n        ],\n        "visual_representation": [\n          ["S", ".", ".", ".", ".", ".", ".", "F"],\n          [".", ".", ".", ".", ".", ".", ".", "."],\n          [".", ".", ".", ".", ".", ".", ".", "."],\n          [".", ".", ".", ".", ".", ".", ".", "."],\n          [".", ".", ".", ".", ".", ".", ".", "."],\n          [".", ".", ".", ".", ".", ".", ".", "."],\n          [".", ".", ".", ".", ".", ".", ".", "."],\n          ["S", ".", ".", ".", ".", ".", ".", "F"]\n        ]\n      }\n    }\n  }\n}'}}
parsed_responses:
[{'message': {'steps': ['- Define the objective of the game.', '- Determine the number of players.', '- Create the game board layout.', '- Establish the rules for player movement.', '- Define how players can score points.', '- Set up any special conditions or events.', '- Outline the winning conditions.', '- Play the game step-by-step until a player reaches 5 points.'], 'solution': {'Create the game board layout': {'board_size': '8x8 grid', 'board_elements': ['Start position for each player', 'Pathways for movement', 'Special tiles (e.g., bonus points, traps)', 'Finish line or goal area'], 'visual_representation': [['S', '.', '.', '.', '.', '.', '.', 'F'], ['.', '.', '.', '.', '.', '.', '.', '.'], ['.', '.', '.', '.', '.', '.', '.', '.'], ['.', '.', '.', '.', '.', '.', '.', '.'], ['.', '.', '.', '.', '.', '.', '.', '.'], ['.', '.', '.', '.', '.', '.', '.', '.'], ['.', '.', '.', '.', '.', '.', '.', '.'], ['S', '.', '.', '.', '.', '.', '.', 'F']]}}}}, {'message': {'steps': ['- Define the objective of the game.', '- Determine the number of players.', '- Create the game board layout.', '- Establish the rules for player movement.', '- Define how players can score points.', '- Set up any special conditions or events.', '- Outline the winning conditions.', '- Play the game step-by-step until a player reaches 5 points.'], 'solution': {'Create the game board layout': {'board_size': '8x8 grid', 'board_elements': ['Start position for each player', 'Pathways for movement', 'Special tiles (e.g., bonus points, traps)', 'Finish line or goal area'], 'visual_representation': [['S', '.', '.', '.', '.', '.', '.', 'F'], ['.', '.', '.', '.', '.', '.', '.', '.'], ['.', '.', '.', '.', '.', '.', '.', '.'], ['.', '.', '.', '.', '.', '.', '.', '.'], ['.', '.', '.', '.', '.', '.', '.', '.'], ['.', '.', '.', '.', '.', '.', '.', '.'], ['.', '.', '.', '.', '.', '.', '.', '.'], ['S', '.', '.', '.', '.', '.', '.', 'F']]}}}}]
response:

Traceback (most recent call last):
  File "/Users/Lukas_1/Library/Mobile Documents/com~apple~CloudDocs/Repos/Oracle/oracle_repo.py", line 361, in openai_request
    response = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/openai/_utils/_utils.py", line 303, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 598, in create
    return self._post(
           ^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/openai/_base_client.py", line 1086, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/openai/_base_client.py", line 846, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/openai/_base_client.py", line 872, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 103, in handle_request
    return self._connection.handle_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 133, in handle_request
    raise exc
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 111, in handle_request
    ) = self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 176, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 212, in _receive_event
    data = self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/ssl.py", line 1263, in recv
    return self.read(buflen)
           ^^^^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/ssl.py", line 1136, in read
    return self._sslobj.read(len)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/0w/pr0ksl1j4n72_489mtlbzlk00000gn/T/ipykernel_51296/1862231808.py", line 4, in <module>
    finished, sub_layer = process_steps(response_outputs, best_response_body, num_step, problem_scope, problem_type, n_models, adaptation_rate, num_steps_proposed, response_outputs_backup, sub_layer)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/folders/0w/pr0ksl1j4n72_489mtlbzlk00000gn/T/ipykernel_51296/3549622454.py", line 20, in process_steps
    orep.openai_request(client, n_models, num_step, system_task, task_step, response, response_outputs)
  File "/Users/Lukas_1/Library/Mobile Documents/com~apple~CloudDocs/Repos/Oracle/oracle_repo.py", line 395, in openai_request
    except openai.error.ServiceUnavailableError as e:
           ^^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 2102, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1310, in structured_traceback
    return FormattedTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1199, in structured_traceback
    return VerboseTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1052, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py", line 978, in format_exception_as_a_whole
    frames.append(self.format_record(record))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py", line 878, in format_record
    frame_info.lines, Colors, self.has_colors, lvals
    ^^^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py", line 712, in lines
    return self._sd.lines
           ^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
                                               ^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/stack_data/core.py", line 698, in lines
    pieces = self.included_pieces
             ^^^^^^^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
                                               ^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/stack_data/core.py", line 649, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
                             ^^^^^^^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
                                               ^^^^^^^^^^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/stack_data/core.py", line 628, in executing_piece
    return only(
           ^^^^^
  File "/Users/Lukas_1/anaconda3/lib/python3.11/site-packages/executing/executing.py", line 164, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0

In [46]:
importlib.reload(orep)

In [23]:
t_df_columns = ["act_max_score", "ag_rationality", "model_type_label", "agent_type_label", "adaptation_rate", "problem_scope_label", "problem_type_label", "num_step", "n_models", "num_steps_proposed", "ratio_steps_left", "error_rate"]
training_data_df = pd.DataFrame(training_data, columns=t_df_columns)
training_data_df

,act_max_score,ag_rationality,model_type_label,agent_type_label,adaptation_rate,problem_scope_label,problem_type_label,num_step,n_models,num_steps_proposed,ratio_steps_left,error_rate
0,0.000000,0.000,0,0,0,0,"[0, 0, 0, 0]",0,0,0,0.000000,0.0
1,32.633882,108.696,2,1,0,1,"[1, 0, 0, 0]",0,2,7,1.000000,0.0
2,32.908800,108.696,2,1,0,1,"[1, 0, 0, 0]",1,2,7,0.857143,0.0
3,32.908800,108.696,2,1,0,1,"[1, 0, 0, 0]",1,2,7,0.857143,0.0
4,32.908800,108.696,2,1,0,1,"[1, 0, 0, 0]",2,2,7,0.714286,0.0
5,32.908800,108.696,2,1,0,1,"[1, 0, 0, 0]",3,2,7,0.571429,0.0
6,32.908800,108.696,2,1,0,1,"[1, 0, 0, 0]",4,2,7,0.428571,0.0
7,32.908800,108.696,2,1,0,1,"[1, 0, 0, 0]",5,2,7,0.285714,0.0
8,32.908800,108.696,2,1,0,1,"[1, 0, 0, 0]",6,2,7,0.142857,0.0
9,32.908800,108.696,2,1,0,1,"[1, 0, 0, 0]",6,2,7,0.142857,0.0
10,32.908800,108.696,2,1,0,1,"[1, 0, 0, 0]",6,2,7,0.142857,0.0

In [27]:
pd.DataFrame(best_response_backup)

,0,1,2,3,4,5,6
0,"{'model_type': 'gpt-4o', 'agent_type': 'LLM', ...",NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,"{'model_type': 'gpt-4o', 'agent_type': 'LLM', ...",NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,"{'model_type': 'gpt-4o', 'agent_type': 'LLM', ...",NaN,NaN,NaN,NaN
3,NaN,"{'model_type': 'gpt-4o', 'agent_type': 'LLM', ...",NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,"{'model_type': 'gpt-4o', 'agent_type': 'LLM', ...",NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,"{'model_type': 'gpt-4o', 'agent_type': 'LLM', ...",NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,"{'model_type': 'gpt-4o', 'agent_type': 'LLM', ...",NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,"{'model_type': 'gpt-4o', 'agent_type': 'LLM', ...",NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,"{'model_type': 'gpt-4o', 'agent_type': 'LLM', ..."
9,NaN,NaN,NaN,NaN,NaN,NaN,"{'model_type': 'gpt-4o', 'agent_type': 'LLM', ..."
10,NaN,NaN,NaN,NaN,NaN,NaN,"{'model_type': 'gpt-4o', 'agent_type': 'LLM', ..."

In [761]:
import pandas as pd
t_df_columns = ["act_max_score", "ag_rationality", "model_type_label", "agent_type_label", "adaptation_rate", "problem_scope_label", "problem_type_label", "num_step", "n_models", "num_steps_proposed", "ratio_steps_left", "error_rate"]
ro_df_columns = ["model_1", "model_2"]
training_data_df = pd.DataFrame(training_data, columns=t_df_columns)
response_outputs_backup_df = pd.DataFrame(response_outputs_backup, columns=ro_df_columns)
best_response_backup_df = pd.DataFrame(best_response_backup, columns=["best_response_backup"])
training_data_df.to_csv("training_data.csv", index=False)
response_outputs_backup_df.to_csv("response_outputs_backup.csv", index=False)

In [28]:
df = pd.DataFrame(best_response_backup)

def consolidate_non_nan_entries(df):
    consolidated_list = []
    for index, row in df.iterrows():
        consolidated_row = {}
        for item in row.dropna():
            consolidated_row.update(item)
        consolidated_list.append(consolidated_row)
    return pd.DataFrame(consolidated_list)

# Consolidate the DataFrame
consolidated_df = consolidate_non_nan_entries(df)
consolidated_df
#consolidated_df.to_csv("best_response_backup.csv", index=False)

   model_type agent_type                                            message
0      gpt-4o        LLM  {\n  "steps": [\n    "- Define the objective o...
1      gpt-4o        LLM  {\n  "message": {\n    "steps": [\n      "- De...
2      gpt-4o        LLM  {\n  "steps": [\n    "- Define the objective o...
3      gpt-4o        LLM  {\n  "message": {\n    "steps": [\n      "- De...
4      gpt-4o        LLM  {\n  "message": {\n    "steps": [\n      "- De...
5      gpt-4o        LLM  {\n  "message": {\n    "steps": [\n      "- De...
6      gpt-4o        LLM  {\n  "message": {\n    "steps": [\n      "- De...
7      gpt-4o        LLM  {\n  "message": {\n    "steps": [\n      "- De...
8      gpt-4o        LLM  {\n  "steps": [\n    "- Define the objective o...
9      gpt-4o        LLM  {\n  "message": {\n    "steps": [\n      "- De...
10     gpt-4o        LLM  {\n  "message": {\n    "steps": [\n      "- Pl...

In [30]:
#response_outputs_backup_df["model_1"][1][1]['message']
#-> use this code to calculate the error rate by comparing the similarities between word vectors. If similaritiy is > 0.95 for t and t+1 then add +1 to error rate and +1 to strike_counter. It strike_counter hits 5, break the loop (possibly ask the model to consider if it is finished).
response_outputs_backup

[[{0: {'model_type': 'gpt-4o',
    'agent_type': 'LLM',
    'message': '{\n  "steps": [\n    "- Define the objective of the game.",\n    "- Determine the number of players.",\n    "- Create the game board layout.",\n    "- Establish the rules for player movement.",\n    "- Define how players can score points.",\n    "- Set up any special rules or conditions.",\n    "- Play the game according to the rules until a player reaches 5 points."\n  ]\n}'}},
  {0: {'model_type': 'gpt-4o',
    'agent_type': 'LLM',
    'message': '{\n  "tasks": [\n    "- Define the objective of the game.",\n    "- Determine the number of players.",\n    "- Create the game board layout.",\n    "- Establish the rules for player movement.",\n    "- Define how players can score points.",\n    "- Set up any special conditions or events.",\n    "- Outline the winning conditions.",\n    "- Play the game step-by-step until a player reaches 5 points."\n  ]\n}'}}],
 [{1: {'model_type': 'gpt-4o',
    'agent_type': 'LLM',
    'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game.",\n      "- Determine the number of players.",\n      "- Create the game board layout.",\n      "- Establish the rules for player movement.",\n      "- Define how players can score points.",\n      "- Set up any special conditions or events.",\n      "- Outline the winning conditions.",\n      "- Play the game step-by-step until a player reaches 5 points."\n    ],\n    "solution": {\n      "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges."\n    }\n  }\n}'}},
  {1: {'model_type': 'gpt-4o',
    'agent_type': 'LLM',
    'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game.",\n      "- Determine the number of players.",\n      "- Create the game board layout.",\n      "- Establish the rules for player movement.",\n      "- Define how players can score points.",\n      "- Set up any special conditions or events.",\n      "- Outline the winning conditions.",\n      "- Play the game step-by-step until a player reaches 5 points."\n    ],\n    "solution": {\n      "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges."\n    }\n  }\n}'}}],
 [{1: {'model_type': 'gpt-4o',
    'agent_type': 'LLM',
    'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game.",\n      "- Determine the number of players.",\n      "- Create the game board layout.",\n      "- Establish the rules for player movement.",\n      "- Define how players can score points.",\n      "- Set up any special conditions or events.",\n      "- Outline the winning conditions.",\n      "- Play the game step-by-step until a player reaches 5 points."\n    ],\n    "solution": {\n      "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges."\n    }\n  }\n}'}},
  {1: {'model_type': 'gpt-4o',
    'agent_type': 'LLM',
    'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game.",\n      "- Determine the number of players.",\n      "- Create the game board layout.",\n      "- Establish the rules for player movement.",\n      "- Define how players can score points.",\n      "- Set up any special conditions or events.",\n      "- Outline the winning conditions.",\n      "- Play the game step-by-step until a player reaches 5 points."\n    ],\n    "solution": {\n      "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges."\n    }\n  }\n}'}}],
 [{2: {'model_type': 'gpt-4o',
    'agent_type': 'LLM',
    'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game.",\n      "- Determine the number of players.",\n      "- Create the game board layout.",\n      "- Establish the rules for player movement.",\n      "- Define how players can score points.",\n      "- Set up any special conditions or events.",\n      "- Outline the winning conditions.",\n      "- Play the game step-by-step until a player reaches 5 points."\n    ],\n    "solution": {\n      "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges.",\n      "number_of_players": 2\n    }\n  }\n}'}},
  {2: {'model_type': 'gpt-4o',
    'agent_type': 'LLM',
    'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game.",\n      "- Determine the number of players.",\n      "- Create the game board layout.",\n      "- Establish the rules for player movement.",\n      "- Define how players can score points.",\n      "- Set up any special conditions or events.",\n      "- Outline the winning conditions.",\n      "- Play the game step-by-step until a player reaches 5 points."\n    ],\n    "solution": {\n      "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges.",\n      "number_of_players": 2\n    }\n  }\n}'}}],
 [{3: {'model_type': 'gpt-4o',
    'agent_type': 'LLM',
    'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game.",\n      "- Determine the number of players.",\n      "- Create the game board layout.",\n      "- Establish the rules for player movement.",\n      "- Define how players can score points.",\n      "- Set up any special conditions or events.",\n      "- Outline the winning conditions.",\n      "- Play the game step-by-step until a player reaches 5 points."\n    ],\n    "solution": {\n      "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges.",\n      "number_of_players": 2,\n      "game_board_layout": {\n        "size": "8x8 grid",\n        "starting_positions": {\n          "player_1": [0, 0],\n          "player_2": [7, 7]\n        },\n        "special_tiles": {\n          "bonus_points": [[2, 2], [5, 5]],\n          "penalty_points": [[3, 3], [4, 4]]\n        },\n        "obstacles": [[1, 1], [6, 6]]\n      }\n    }\n  }\n}'}},
  {3: {'model_type': 'gpt-4o',
    'agent_type': 'LLM',
    'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game.",\n      "- Determine the number of players.",\n      "- Create the game board layout.",\n      "- Establish the rules for player movement.",\n      "- Define how players can score points.",\n      "- Set up any special conditions or events.",\n      "- Outline the winning conditions.",\n      "- Play the game step-by-step until a player reaches 5 points."\n    ],\n    "solution": {\n      "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges.",\n      "number_of_players": 2,\n      "game_board_layout": {\n        "size": "8x8 grid",\n        "starting_positions": {\n          "player_1": [0, 0],\n          "player_2": [7, 7]\n        },\n        "special_tiles": {\n          "bonus_points": [[2, 2], [5, 5]],\n          "penalty_points": [[3, 3], [4, 4]]\n        },\n        "obstacles": [[1, 1], [6, 6]]\n      }\n    }\n  }\n}'}}],
 [{4: {'model_type': 'gpt-4o',
    'agent_type': 'LLM',
    'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game.",\n      "- Determine the number of players.",\n      "- Create the game board layout.",\n      "- Establish the rules for player movement.",\n      "- Define how players can score points.",\n      "- Set up any special conditions or events.",\n      "- Outline the winning conditions.",\n      "- Play the game step-by-step until a player reaches 5 points."\n    ],\n    "solution": {\n      "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges.",\n      "number_of_players": 2,\n      "game_board_layout": {\n        "size": "8x8 grid",\n        "starting_positions": {\n          "player_1": [0, 0],\n          "player_2": [7, 7]\n        },\n        "special_tiles": {\n          "bonus_points": [\n            [2, 2],\n            [5, 5]\n          ],\n          "penalty_points": [\n            [3, 3],\n            [4, 4]\n          ]\n        },\n        "obstacles": [\n          [1, 1],\n          [6, 6]\n        ]\n      },\n      "rules_for_player_movement": {\n        "movement_options": ["up", "down", "left", "right"],\n        "movement_restrictions": "Players cannot move through obstacles or off the board.",\n        "movement_cost": "Each move costs 1 action point. Players have 3 action points per turn."\n      }\n    }\n  }\n}'}},
  {4: {'model_type': 'gpt-4o',
    'agent_type': 'LLM',
    'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game.",\n      "- Determine the number of players.",\n      "- Create the game board layout.",\n      "- Establish the rules for player movement.",\n      "- Define how players can score points.",\n      "- Set up any special conditions or events.",\n      "- Outline the winning conditions.",\n      "- Play the game step-by-step until a player reaches 5 points."\n    ],\n    "solution": {\n      "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges.",\n      "number_of_players": 2,\n      "game_board_layout": {\n        "size": "8x8 grid",\n        "starting_positions": {\n          "player_1": [0, 0],\n          "player_2": [7, 7]\n        },\n        "special_tiles": {\n          "bonus_points": [\n            [2, 2],\n            [5, 5]\n          ],\n          "penalty_points": [\n            [3, 3],\n            [4, 4]\n          ]\n        },\n        "obstacles": [\n          [1, 1],\n          [6, 6]\n        ]\n      },\n      "rules_for_player_movement": {\n        "movement_options": ["up", "down", "left", "right"],\n        "movement_restrictions": "Players cannot move through obstacles or off the board.",\n        "movement_cost": "Each move costs 1 action point. Players have 3 action points per turn."\n      },\n      "scoring": {\n        "bonus_points": 1,\n        "penalty_points": -1\n      },\n      "special_conditions": {\n        "bonus_points_tiles": "Landing on a bonus point tile grants 1 point.",\n        "penalty_points_tiles": "Landing on a penalty point tile deducts 1 point."\n      },\n      "winning_conditions": "The first player to reach 5 points wins the game."\n    }\n  }\n}'}}],
 [{5: {'model_type': 'gpt-4o',
    'agent_type': 'LLM',
    'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game.",\n      "- Determine the number of players.",\n      "- Create the game board layout.",\n      "- Establish the rules for player movement.",\n      "- Define how players can score points.",\n      "- Set up any special conditions or events.",\n      "- Outline the winning conditions.",\n      "- Play the game step-by-step until a player reaches 5 points."\n    ],\n    "solution": {\n      "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges.",\n      "number_of_players": 2,\n      "game_board_layout": {\n        "size": "8x8 grid",\n        "starting_positions": {\n          "player_1": [0, 0],\n          "player_2": [7, 7]\n        },\n        "special_tiles": {\n          "bonus_points": [[2, 2], [5, 5]],\n          "penalty_points": [[3, 3], [4, 4]]\n        },\n        "obstacles": [[1, 1], [6, 6]]\n      },\n      "rules_for_player_movement": {\n        "movement_options": ["up", "down", "left", "right"],\n        "movement_restrictions": "Players cannot move through obstacles or off the board.",\n        "movement_cost": "Each move costs 1 action point. Players have 3 action points per turn."\n      },\n      "how_players_score_points": {\n        "scoring_mechanism": [\n          "Players score 1 point for landing on a bonus point tile.",\n          "Players lose 1 point for landing on a penalty point tile.",\n          "Players can also score 1 point by reaching the opponent\'s starting position."\n        ]\n      }\n    }\n  }\n}'}},
  {5: {'model_type': 'gpt-4o',
    'agent_type': 'LLM',
    'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game.",\n      "- Determine the number of players.",\n      "- Create the game board layout.",\n      "- Establish the rules for player movement.",\n      "- Define how players can score points.",\n      "- Set up any special conditions or events.",\n      "- Outline the winning conditions.",\n      "- Play the game step-by-step until a player reaches 5 points."\n    ],\n    "solution": {\n      "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges.",\n      "number_of_players": 2,\n      "game_board_layout": {\n        "size": "8x8 grid",\n        "starting_positions": {\n          "player_1": [0, 0],\n          "player_2": [7, 7]\n        },\n        "special_tiles": {\n          "bonus_points": [[2, 2], [5, 5]],\n          "penalty_points": [[3, 3], [4, 4]]\n        },\n        "obstacles": [[1, 1], [6, 6]]\n      },\n      "rules_for_player_movement": {\n        "movement_options": ["up", "down", "left", "right"],\n        "movement_restrictions": "Players cannot move through obstacles or off the board.",\n        "movement_cost": "Each move costs 1 action point. Players have 3 action points per turn."\n      },\n      "how_players_score_points": {\n        "scoring_mechanism": [\n          "Players score 1 point for landing on a bonus point tile.",\n          "Players lose 1 point for landing on a penalty point tile.",\n          "Players can also score 1 point by reaching the opponent\'s starting position."\n        ]\n      }\n    }\n  }\n}'}}],
 [{6: {'model_type': 'gpt-4o',
    'agent_type': 'LLM',
    'message': '{\n  "steps": [\n    "- Define the objective of the game.",\n    "- Determine the number of players.",\n    "- Create the game board layout.",\n    "- Establish the rules for player movement.",\n    "- Define how players can score points.",\n    "- Set up any special conditions or events.",\n    "- Outline the winning conditions.",\n    "- Play the game step-by-step until a player reaches 5 points."\n  ],\n  "solution": {\n    "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges.",\n    "number_of_players": 2,\n    "game_board_layout": {\n      "size": "8x8 grid",\n      "starting_positions": {\n        "player_1": [0, 0],\n        "player_2": [7, 7]\n      },\n      "special_tiles": {\n        "bonus_points": [[2, 2], [5, 5]],\n        "penalty_points": [[3, 3], [4, 4]]\n      },\n      "obstacles": [[1, 1], [6, 6]]\n    },\n    "rules_for_player_movement": {\n      "movement_options": ["up", "down", "left", "right"],\n      "movement_restrictions": "Players cannot move through obstacles or off the board.",\n      "movement_cost": "Each move costs 1 action point. Players have 3 action points per turn."\n    },\n    "how_players_score_points": {\n      "scoring_mechanism": [\n        "Players score 1 point for landing on a bonus point tile.",\n        "Players lose 1 point for landing on a penalty point tile.",\n        "Players can also score 1 point by reaching the opponent\'s starting position."\n      ]\n    },\n    "special_conditions_or_events": {\n      "power_ups": {\n        "description": "Players can collect power-ups that grant special abilities.",\n        "locations": [[0, 4], [7, 3]],\n        "abilities": ["extra action point", "move through obstacles for one turn"]\n      },\n      "random_events": {\n        "description": "Random events can occur at the end of each turn, affecting the game board or players.",\n        "examples": ["board tiles shift positions", "players swap positions"]\n      }\n    }\n  }\n}'}},
  {6: {'model_type': 'gpt-4o',
    'agent_type': 'LLM',
    'message': '{\n  "steps": [\n    "- Define the objective of the game.",\n    "- Determine the number of players.",\n    "- Create the game board layout.",\n    "- Establish the rules for player movement.",\n    "- Define how players can score points.",\n    "- Set up any special conditions or events.",\n    "- Outline the winning conditions.",\n    "- Play the game step-by-step until a player reaches 5 points."\n  ],\n  "solution": {\n    "objective": "The objective of the game is to be the first player to reach 5 points by strategically moving across the game board and overcoming various challenges.",\n    "number_of_players": 2,\n    "game_board_layout": {\n      "size": "8x8 grid",\n      "starting_positions": {\n        "player_1": [0, 0],\n        "player_2": [7, 7]\n      },\n      "special_tiles": {\n        "bonus_points": [[2, 2], [5, 5]],\n        "penalty_points": [[3, 3], [4, 4]]\n      },\n      "obstacles": [[1, 1], [6, 6]]\n    },\n    "rules_for_player_movement": {\n      "movement_options": ["up", "down", "left", "right"],\n      "movement_restrictions": "Players cannot move through obstacles or off the board.",\n      "movement_cost": "Each move costs 1 action point. Players have 3 action points per turn."\n    },\n    "how_players_score_points": {\n      "scoring_mechanism": [\n        "Players score 1 point for landing on a bonus point tile.",\n        "Players lose 1 point for landing on a penalty point tile.",\n        "Players can also score 1 point by reaching the opponent\'s starting position."\n      ]\n    },\n    "special_conditions_or_events": {\n      "power_ups": {\n        "description": "Players can collect power-ups that grant special abilities.",\n        "locations": [[0, 4], [7, 3]],\n        "abilities": ["extra action point", "move through obstacles for one turn"]\n      },\n      "random_events": {\n        "description": "Random events can occur at the end of each turn, affecting the game board or players.",\n        "examples": ["board tiles shift positions", "players swap positions"]\n      }\n    },\n    "winning_conditions": "The first player to reach 5 points wins the game."\n  }\n}'}}],
 [{6: {'model_type': 'gpt-4o',
    'agent_type': 'LLM',

In [ ]:
import pandas as pd
t_df_columns = ["act_max_score", "ag_rationality", "model_type_label", "agent_type_label", "adaptation_rate", "problem_scope_label", "problem_type_label", "num_step", "n_models", "num_steps_proposed", "ratio_steps_left", "error_rate"]
ro_df_columns = ["model_1", "model_2"]
training_data_df = pd.DataFrame(training_data, columns=t_df_columns)
response_outputs_backup_df = pd.DataFrame(response_outputs_backup, columns=ro_df_columns)
best_response_backup_df = pd.DataFrame(best_response_backup, columns=["best_response_backup"])
training_data_df.to_csv("training_data.csv", index=False)
response_outputs_backup_df.to_csv("response_outputs_backup.csv", index=False)

In [774]:
for item in best_response_backup:
    print(item)

{0: {'model_type': 'gpt-4o', 'agent_type': 'LLM', 'message': '{\n  "steps": [\n    "- Define the objective of the game.",\n    "- Determine the number of players.",\n    "- Establish the game board layout.",\n    "- Create the rules for player movement.",\n    "- Develop the scoring system.",\n    "- Outline the win conditions.",\n    "- Play the game until a player reaches 5 points."\n  ]\n}'}}
{1: {'model_type': 'gpt-4o', 'agent_type': 'LLM', 'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game",\n      "- Establish the rules for player actions",\n      "- Create a scoring system",\n      "- Determine the conditions for winning",\n      "- Play the game according to the rules",\n      "- Track the scores of each player",\n      "- Continue playing until a player reaches 5 points"\n    ],\n    "solution": {\n      "objective": "The objective of the game is to be the first player to reach 5 points by following the established rules and scoring system."\n    }\n  }\n}'}}
{2: {'model_type': 'gpt-4o', 'agent_type': 'LLM', 'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game",\n      "- Establish the rules for player actions",\n      "- Create a scoring system",\n      "- Determine the conditions for winning",\n      "- Play the game according to the rules",\n      "- Track the scores of each player",\n      "- Continue playing until a player reaches 5 points",\n      "- Determine the number of players"\n    ],\n    "solution": {\n      "objective": "The objective of the game is to be the first player to reach 5 points by following the established rules and scoring system.",\n      "number_of_players": 2\n    }\n  }\n}'}}
{3: {'model_type': 'gpt-4o', 'agent_type': 'LLM', 'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game",\n      "- Establish the rules for player actions",\n      "- Create a scoring system",\n      "- Determine the conditions for winning",\n      "- Play the game according to the rules",\n      "- Track the scores of each player",\n      "- Continue playing until a player reaches 5 points",\n      "- Determine the number of players",\n      "- Establish the game board layout"\n    ],\n    "solution": {\n      "objective": "The objective of the game is to be the first player to reach 5 points by following the established rules and scoring system.",\n      "number_of_players": 2,\n      "game_board_layout": "The game board consists of a 5x5 grid where each player starts at opposite corners. Players move one space per turn, either horizontally or vertically. The center space is a special scoring zone where players can earn extra points."\n    }\n  }\n}'}}
{4: {'model_type': 'gpt-4o', 'agent_type': 'LLM', 'message': '{\n  "steps": [\n    "- Define the objective of the game",\n    "- Establish the rules for player actions",\n    "- Create a scoring system",\n    "- Determine the conditions for winning",\n    "- Play the game according to the rules",\n    "- Track the scores of each player",\n    "- Continue playing until a player reaches 5 points",\n    "- Determine the number of players",\n    "- Establish the game board layout"\n  ],\n  "solution": {\n    "objective": "The objective of the game is to be the first player to reach 5 points by following the established rules and scoring system.",\n    "number_of_players": 2,\n    "game_board_layout": "The game board consists of a 5x5 grid where each player starts at opposite corners. Players move one space per turn, either horizontally or vertically. The center space is a special scoring zone where players can earn extra points."\n  },\n  "message": {\n    "rules_for_player_movement": {\n      "movement_options": [\n        "Players can move one space per turn.",\n        "Movement can be either horizontally or vertically.",\n        "Players cannot move diagonally.",\n        "Players cannot move into a space occupied by another player."\n      ],\n      "special_conditions": [\n        "If a player moves into the center space, they earn an extra point.",\n        "Players must follow the established turn order."\n      ]\n    }\n  }\n}'}}
{5: {'model_type': 'gpt-4o', 'agent_type': 'LLM', 'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game",\n      "- Establish the rules for player actions",\n      "- Create a scoring system",\n      "- Determine the conditions for winning",\n      "- Play the game according to the rules",\n      "- Track the scores of each player",\n      "- Continue playing until a player reaches 5 points",\n      "- Determine the number of players",\n      "- Establish the game board layout"\n    ],\n    "solution": {\n      "scoring_system": {\n        "description": "The scoring system will be based on the completion of specific tasks or objectives within the game. Points will be awarded as follows:",\n        "points_awarded": [\n          {\n            "task": "Completing a minor objective",\n            "points": 1\n          },\n          {\n            "task": "Completing a major objective",\n            "points": 2\n          },\n          {\n            "task": "Winning a round",\n            "points": 3\n          }\n        ],\n        "additional_rules": [\n          "Players can lose points for breaking the rules or failing to complete objectives.",\n          "Bonus points can be awarded for exceptional performance or creativity."\n        ]\n      }\n    }\n  }\n}'}}
{6: {'model_type': 'gpt-4o', 'agent_type': 'LLM', 'message': '{\n  "message": {\n    "steps": [\n      "- Define the objective of the game",\n      "- Establish the rules for player actions",\n      "- Create a scoring system",\n      "- Determine the conditions for winning",\n      "- Play the game according to the rules",\n      "- Track the scores of each player",\n      "- Continue playing until a player reaches 5 points",\n      "- Determine the number of players",\n      "- Establish the game board layout"\n    ],\n    "solution": {\n      "scoring_system": {\n        "description": "The scoring system will be based on the completion of specific tasks or objectives within the game. Points will be awarded as follows:",\n        "points_awarded": [\n          {\n            "task": "Completing a minor objective",\n            "points": 1\n          },\n          {\n            "task": "Completing a major objective",\n            "points": 2\n          },\n          {\n            "task": "Winning a round",\n            "points": 3\n          }\n        ],\n        "additional_rules": [\n          "Players can lose points for breaking the rules or failing to complete objectives.",\n          "Bonus points can be awarded for exceptional performance or creativity."\n        ]\n      },\n      "win_conditions": {\n        "description": "The win conditions will be based on the accumulation of points and the completion of specific objectives.",\n        "conditions": [\n          "A player wins the game by being the first to reach 5 points.",\n          "If multiple players reach 5 points in the same round, the player with the most major objectives completed wins.",\n          "In the event of a tie in major objectives, the player with the most minor objectives completed wins.",\n          "If there is still a tie, the game continues until one player surpasses the others in points."\n        ]\n      }\n    }\n  }\n}'}}

In [771]:
# Function to flatten the dictionary
def flatten_dict(d, parent_key='', sep='_'):
    items = []
    for k, v in d.items():
        new_key = f"{parent_key}{sep}{k}" if parent_key else k
        if isinstance(v, dict):
            items.extend(flatten_dict(v, new_key, sep=sep).items())
        elif isinstance(v, list):
            for i, item in enumerate(v):
                items.extend(flatten_dict({f"{new_key}{sep}{i}": item}).items())
        else:
            items.append((new_key, v))
    return dict(items)

# Flatten the dictionary
flattened_data = flatten_dict(best_response_backup)

best_response_backup_df = pd.DataFrame([flattened_data])

del(flattened_data)

AttributeError: 'list' object has no attribute 'items'

In [764]:
best_response_backup_df = pd.DataFrame(best_response_backup, columns=["best_response_backup"])
best_response_backup_df

   best_response_backup
0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   NaN
5                   NaN
6                   NaN

DEFINE THE NETWORK

In [ ]:
# Assume generate_feature_vector function is defined as in previous messages

class LSTMNetwork(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(LSTMNetwork, self).__init__()
        self.hidden_size = hidden_size
        
        self.lstm = nn.LSTM(input_size, hidden_size, batch_first=True)
        self.fc = nn.Linear(hidden_size, 1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, x):
        h0 = torch.zeros(1, x.size(0), self.hidden_size).to(x.device)
        c0 = torch.zeros(1, x.size(0), self.hidden_size).to(x.device)
        
        out, _ = self.lstm(x, (h0, c0))
        out = out[:, -1, :]  # Get the last time step output
        out = self.fc(out)
        out = self.sigmoid(out)
        return out

class FeatureDataset(Dataset):
    def __init__(self, feature_vectors, labels):
        self.feature_vectors = feature_vectors
        self.labels = labels
    
    def __len__(self):
        return len(self.feature_vectors)
    
    def __getitem__(self, idx):
        return torch.tensor(self.feature_vectors[idx], dtype=torch.float32), torch.tensor(self.labels[idx], dtype=torch.float32)

# Example feature vectors and labels
feature_vectors = [orep.generate_feature_vector(env_params, responses, api_response_text, rationality_params, accuracy, benchmark_performance_score, messages) for _ in range(100)]
labels = np.random.randint(0, 2, size=100)  # Binary labels: 1 for success, 0 for failure

# Create dataset and dataloader
dataset = FeatureDataset(feature_vectors, labels)
dataloader = DataLoader(dataset, batch_size=10, shuffle=True)

# Hyperparameters
input_size = len(feature_vectors[0])  # Number of features in the feature vector
hidden_size = 15

# Initialize the network, loss function, and optimizer
model = LSTMNetwork(input_size, hidden_size)
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

TRAIN THE NETWORK

In [ ]:
# Training loop
num_epochs = 20
for epoch in range(num_epochs):
    for i, (features, labels) in enumerate(dataloader):
        # Reshape input to (batch_size, seq_length, input_size)
        features = features.unsqueeze(1)
        
        # Forward pass
        outputs = model(features)
        loss = criterion(outputs.squeeze(), labels)
        
        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    
    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

print('Training completed.')

PREDICT AND EVALUATE SUCCESS

In [ ]:
def predict_success(model, feature_vector, threshold=0.55):
    model.eval()
    feature_tensor = torch.tensor(feature_vector, dtype=torch.float32).unsqueeze(0).unsqueeze(0)  # Shape (1, 1, input_size)
    with torch.no_grad():
        probability = model(feature_tensor).item()
    return probability, probability > threshold

# Example usage
test_feature_vector = generate_feature_vector(env_params, responses, api_response_text, rationality_params, accuracy, benchmark_performance_score, messages)
probability, is_success = predict_success(model, test_feature_vector)
print(f'Probability of Success: {probability:.4f}, Success: {is_success}')